### ISSUE TITLE
property sequence not preserved

### ISSUE THREAD

**Issue by yankeeinlondon** [blcook223/DummyData#2]
It would be nice if the sequence of properties of the model was preserved in the generated data. This would often increase the readability of the output data. Not sure if this is a "defect" or "feature request".

**Comment by blcook223** [comment]
This is resolved on `develop` branch (cf. cfedf83e4dcf107704feb5f5b9f1134613c529f6) and will be included in the next release.

**Comment by yankeeinlondon** [comment]
great, thanks
